### ISSUE TITLE
[BUG] Creating a new Schema results in the app hanging for some time

### ISSUE THREAD

**Issue by KostasFeg** [ConduitPlatform/Conduit#57]
**Describe the bug**
Creating a new Schema takes longer than it should.

**To Reproduce**
1. Go to 'Database' tab
2. Click on 'Create Schema'
3. Fill the Schema fields and press save

**Expected behavior**
Performing an action it may be normal to have a couple of seconds of delay but any longer than that and it should be considered a bug

**Screenshots**

**Environment (please complete the following information):**
 - Chrome 98 on a Windows 11 PC

**Comment by kkopanidis** [comment]
@kon14 this seems to be a router issue and not a Database/CMS issue. As I've seen from logs the router was registering the routes of each schema every 1-2 seconds. So it required almost 30 or so seconds to register all schemas. 

We need to add some probes there and see which operation is struggling. I'm guessing that we're having delays due to graphql parsing the routes, and then express hangs completely while trying to process the new routes. But we need to verify this.
